# Generated by Django 4.2.11 on 2024-04-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_entry_owner_alter_entry_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
