# Generated by Django 4.2.11 on 2024-04-02 07:11

from django.db import migrations
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.recipe'),
            preserve_default=False,
        ),
    ]
