# Generated by Django 4.2.11 on 2024-04-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0007_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
